name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  manubot:
    name: Manubot
    runs-on: self-hosted
    env:
      GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
